name: "Godot HTML5 Export & Deploy"

on:
  push:
    branches:
      - main # Passe dies an, falls dein Branch "master" heißt!

permissions:
  contents: write

jobs:
  export-and-deploy:
    runs-on: ubuntu-latest
    name: Export and Deploy Game
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Godot Export
        uses: abarrientos/godot-export-action@v1
        with:
          godot_version: "4.2.2"
          export_type: "web"
          project_folder: "."

      - name: Deploy to GitHub Pages
        uses: Peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web