name: "Godot HTML5 Export & Deploy"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  export-and-deploy:
    runs-on: ubuntu-latest
    name: Export and Deploy Game
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Godot Export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
          relative_project_path: "./"
          use_preset_export_path: true
          archive_output: false

      - name: Move Files to Root Export Dir
        run: |
          if [ -d "./build/web/Web" ]; then
            mv ./build/web/Web/* ./build/web/
            rm -rf ./build/web/Web
          fi

      - name: Download coi-serviceworker
        run: |
          curl -sL https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.js -o ./build/web/coi-serviceworker.js

      - name: Deploy to GitHub Pages
        uses: Peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web